"""Build src/lib/engine/everyday_words.ts - the words AI answers use as
ordinary lowercase English (r13, 2026-10-02 review).

Brand checks need to tell an everyday word that happens to be a brand name
("Ring", "Nothing", "Chase", "Purple") from a coined one ("Hulu", "Asana").
Answer engines capitalize brand names and write everyday words in lowercase,
so lowercase MID-SENTENCE use across the response vault is the signal: a
word seen lowercase at least MIN_LOWER times is everyday. Sentence starts,
list markers and domain fragments ("trello.com") are excluded. Reads the
immutable vault only; rerun to refresh:
  python3 scripts/build_everyday_words.py
"""
import gzip, json, glob, re, collections, os

MIN_LOWER = 20
VAULT = os.path.expanduser("~/Documents/procerno_response_vault/*.jsonl.gz")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "engine", "everyday_words.ts")

lower = collections.Counter()
runs, answers = set(), 0
tok = re.compile(r"(?<=[\s(\"'])([A-Za-z][a-z0-9]*)(?![A-Za-z0-9]|\.[a-z])")
for f in sorted(glob.glob(VAULT)):
    run = os.path.basename(f).rsplit("_", 2)[0]
    if run in runs:
        continue  # repeated exports of the same run
    runs.add(run)
    with gzip.open(f, "rt") as fh:
        for line in fh:
            r = json.loads(line)
            if r.get("kind") == "run_meta":
                continue
            t = r.get("text")
            if not isinstance(t, str):
                continue
            answers += 1
            # mask sentence/list starts so their capitals never count
            t = re.sub(r"(^|[.!?:\n]\s*|[-*#>]\s+|\d+\.\s+)(?=[A-Za-z])", lambda m: m.group(1) + "\x00", t)
            for m in tok.finditer(t):
                w = m.group(1)
                if w[0].islower():
                    lower[w] += 1

words = sorted(w for w, c in lower.items() if c >= MIN_LOWER and len(w) >= 3)
with open(OUT, "w") as fh:
    fh.write("// GENERATED by scripts/build_everyday_words.py - do not edit by hand.\n")
    fh.write(f"// {len(words)} words seen lowercase mid-sentence >= {MIN_LOWER} times across {answers} vault answers ({len(runs)} runs).\n")
    fh.write("// A brand word in this set is an everyday word: it names the brand only when capitalized.\n")
    fh.write("export const EVERYDAY_WORDS: ReadonlySet<string> = new Set(\n  \"")
    fh.write(" ".join(words))
    fh.write("\".split(\" \")\n);\n")
print(f"{len(words)} words from {answers} answers ({len(runs)} runs) -> {os.path.normpath(OUT)}")
