"""Build src/lib/engine/everyday_words.ts - the words AI answers use as
ordinary lowercase English (r13, 2026-10-02 review).

Brand checks need to tell an everyday word that happens to be a brand name
("Ring", "Nothing", "Chase", "Purple") from a coined one ("Hulu", "Asana").
Answer engines capitalize brand names and write everyday words in lowercase,
so lowercase MID-SENTENCE use across the response vault is the signal: a
word is everyday when it is seen lowercase at least MIN_LOWER times AND
lowercase is at least MIN_SHARE of its mid-sentence uses. The share is the
load-bearing test (review 2026-10-02): an absolute count alone admitted
"jira", "netflix", "apple", "pixel" - brands written capitalized tens of
thousands of times whose lowercase uses are URLs and code paths - and the
lexicon then blinded the blind-cell leak check to the targets themselves. Sentence starts,
list markers and domain fragments ("trello.com") are excluded. Reads the
immutable vault only; rerun to refresh:
  python3 scripts/build_everyday_words.py
"""
import gzip, json, glob, re, collections, os

MIN_LOWER = 20
MIN_SHARE = 0.30
VAULT = os.path.expanduser("~/Documents/procerno_response_vault/*.jsonl.gz")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "engine", "everyday_words.ts")

lower = collections.Counter()
upper = collections.Counter()
runs, answers = set(), 0
tok = re.compile(r"(?<=[\s(\"'])([A-Za-z][a-z0-9]*)(?![A-Za-z0-9]|\.[a-z])")
for f in sorted(glob.glob(VAULT)):
    run = os.path.basename(f).rsplit("_", 2)[0]
    if run in runs:
        continue  # repeated exports of the same run
    runs.add(run)
    with gzip.open(f, "rt") as fh:
        for line in fh:
            r = json.loads(line)
            if r.get("kind") == "run_meta":
                continue
            t = r.get("text")
            if not isinstance(t, str):
                continue
            answers += 1
            # mask sentence/list starts so their capitals never count
            t = re.sub(r"(^|[.!?:\n]\s*|[-*#>]\s+|\d+\.\s+)(?=[A-Za-z])", lambda m: m.group(1) + "\x00", t)
            for m in tok.finditer(t):
                w = m.group(1)
                if w[0].islower():
                    lower[w] += 1
                else:
                    upper[w.lower()] += 1

common = sorted(w for w, c in lower.items() if c >= MIN_LOWER and len(w) >= 3)
words = [w for w in common if lower[w] / (lower[w] + upper[w]) >= MIN_SHARE]
# Common words whose mid-sentence uses are mostly CAPITALIZED: brand names
# (jira, netflix, apple, pixel) and brand-heavy words (chase, gold, linear).
brand_dominated = sorted(set(common) - set(words))
import sys
if "--show" in sys.argv:
    for w in sys.argv[sys.argv.index("--show") + 1:]:
        lo, up = lower[w], upper[w]
        print(f"{w}: lower={lo} cap={up} share={lo / max(1, lo + up):.2f} common={w in set(common)} everyday={w in set(words)}")
with open(OUT, "w") as fh:
    fh.write("// GENERATED by scripts/build_everyday_words.py - do not edit by hand.\n")
    fh.write(f"// From {answers} vault answers ({len(runs)} runs). COMMON_WORDS: seen lowercase mid-sentence >= {MIN_LOWER} times ({len(common)}).\n")
    fh.write(f"// BRAND_DOMINATED: common words that are still < {MIN_SHARE:.0%} lowercase mid-sentence - brand names and brand-heavy words ({len(brand_dominated)}).\n")
    fh.write("// A label word (a brand's own name or a word of it) is everyday when COMMON and not BRAND_DOMINATED;\n")
    fh.write("// an alias that is not a label word is everyday when COMMON (\"gold\" for American Express).\n")
    for name, ws in (("COMMON_WORDS", common), ("BRAND_DOMINATED", brand_dominated)):
        fh.write(f"export const {name}: ReadonlySet<string> = new Set(\n  \"")
        fh.write(" ".join(ws))
        fh.write("\".split(\" \")\n);\n")
print(f"{len(common)} common / {len(brand_dominated)} brand-dominated from {answers} answers ({len(runs)} runs) -> {os.path.normpath(OUT)}")
